version: '3.8'

services:
  nocturne-app:
    image: node:22-alpine
    container_name: nocturne-sync-server
    user: root  # 强制以 root 运行，解决群晖权限导致的路径解析失败
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    working_dir: /app
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.31.250
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=A9878480a！
      - DB_NAME=nocturne_sync
      - JWT_SECRET=nocturne_reader_secret_key
    # 终极启动指令：检查文件 -> 清理冲突 -> 安装 -> 编译
    command: sh -c "ls -R /app/src && npm config set registry https://registry.npmmirror.com && npm install --include=dev --legacy-peer-deps && npm run build && npm start"

networks:
  default:
    name: nocturne-network
